version: "2"
services:
  orthanc-under-tests:
    image: orthanc-under-tests 
    depends_on:
      - orthanc-db
    environment:
      ORTHANC__ODBC__INDEX_CONNECTION_STRING: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:orthanc-db,1433;Database=orthanctest;Uid=sa;Pwd=MyStrOngPa55word!;Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;"
      ORTHANC__ODBC__STORAGE_CONNECTION_STRING: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:orthanc-db,1433;Database=orthanctest;Uid=sa;Pwd=MyStrOngPa55word!;Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;"
      ORTHANC__ODBC__ENABLE_INDEX: "true"
      ORTHANC__ODBC__ENABLE_STORAGE: "true"
      VERBOSE_STARTUP: "true"
      VERBOSE_ENABLED: "false"

  orthanc-tests:
    image: orthanc-tests
    depends_on:
      - orthanc-under-tests

  orthanc-db:
    build: sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyStrOngPa55word!"
