version: "2"
services:
  orthanc-under-tests:
    image: orthanc-under-tests
    environment:
      - ORTHANC__STORAGE_COMPRESSION=true

  orthanc-tests:
    image: orthanc-tests
    depends_on:
      - orthanc-under-tests

