name: all-builds

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: 
      - '*'
    tags:
      - '*'

  pull_request:
    branches: [ master ]


jobs:
  pre-build:
    uses: ./.github/workflows/pre-build.yml

  build-stone-wasm-stable:
    needs: [pre-build]
    uses: ./.github/workflows/build-stone-wasm.yml
    with:
      is_tag: ${{ needs.pre-build.outputs.is_tag }}
      stable_unstable: stable
      current_branch_tag: ${{ needs.pre-build.outputs.current_branch_tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-stone-wasm-unstable:
    needs: [pre-build]
    uses: ./.github/workflows/build-stone-wasm.yml
    with:
      is_tag: ${{ needs.pre-build.outputs.is_tag }}
      stable_unstable: unstable
      current_branch_tag: ${{ needs.pre-build.outputs.current_branch_tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  osx-stable-build:
    needs: [pre-build, build-stone-wasm-stable]
    uses: ./.github/workflows/build-osx-binaries.yml
    with:
      is_tag: ${{ needs.pre-build.outputs.is_tag }}
      stable_unstable: stable
      current_branch_tag: ${{ needs.pre-build.outputs.current_branch_tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  osx-unstable-build:
    needs: [pre-build, build-stone-wasm-unstable]
    uses: ./.github/workflows/build-osx-binaries.yml
    with:
      is_tag: ${{ needs.pre-build.outputs.is_tag }}
      stable_unstable: unstable
      current_branch_tag: ${{ needs.pre-build.outputs.current_branch_tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  osx-stable-package:
    needs: [pre-build, osx-stable-build]
    uses: ./.github/workflows/build-osx-package.yml
    with:
      is_tag: ${{ needs.pre-build.outputs.is_tag }}
      stable_unstable: stable
      current_branch_tag: ${{ needs.pre-build.outputs.current_branch_tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  osx-unstable-package:
    needs: [pre-build, osx-unstable-build]
    uses: ./.github/workflows/build-osx-package.yml
    with:
      is_tag: ${{ needs.pre-build.outputs.is_tag }}
      stable_unstable: unstable
      current_branch_tag: ${{ needs.pre-build.outputs.current_branch_tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  build-windows-installer:
    needs: [pre-build] #, TODO: build win binaries as well build-win-binaries-unstable]
    uses: ./.github/workflows/build-windows-installer.yml
    with:
      is_tag: ${{ needs.pre-build.outputs.is_tag }}
      stable_unstable: unstable
      current_branch_tag: ${{ needs.pre-build.outputs.current_branch_tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  build-docker:
    needs: [pre-build]
    uses: ./.github/workflows/build-docker.yml
    with:
      is_tag: ${{ needs.pre-build.outputs.is_tag }}
      current_branch_tag: ${{ needs.pre-build.outputs.current_branch_tag }}
    secrets:
      docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      docker_hub_token: ${{ secrets.DOCKERHUB_TOKEN }}


