name: build and release

on:
  push:
    branches: 
      - '*'
    tags:
      - '*'

  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: "ubuntu-latest"

    steps:
    
    - uses: actions/checkout@v2

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    
    - name: Build the runner base Docker image
      run: docker build --progress=plain -t osimis/orthanc-runner-base:current docker/orthanc-runner-base/

    - name: Build the builder base Docker image
      run: docker build --progress=plain -t osimis/orthanc-builder-base:current docker/orthanc-builder-base/

    - name: Build the osimis/orthanc Docker image
      run: docker build --progress=plain -t osimis/orthanc:current -f docker/orthanc/Dockerfile docker/orthanc/

    - name: Tag with current commit ref
      run: docker tag osimis/orthanc:current osimis/orthanc:${{ github.ref }}