on:
  workflow_call:
    inputs:
      is_tag:
        description: 'Is a Git Tag'
        type: string
        required: true
      current_branch_tag:
        description: 'Git branch or Tag'
        type: string
        required: true
    secrets:
      docker_hub_username:
        required: true
      docker_hub_token:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true



jobs:
  build-docker-stable:
    name: build-docker-stable
    uses: ./.github/workflows/build-docker.yml
    with:
      runner: ${{ matrix.config.runner }}
      runner_type: ${{ matrix.config.runnerType }}
      platform: ${{ matrix.config.platform }}
      stable_unstable: ${{ matrix.config.stableUnstable }}
      current_branch_tag: ${{ inputs.current_branch_tag }}
      is_tag: ${{ inputs.is_tag }}
    secrets:
      docker_hub_username: ${{ secrets.docker_hub_username }}
      docker_hub_token: ${{ secrets.docker_hub_token }}
      aws_access_key_id: ${{ secrets.aws_access_key_id }}
      aws_secret_access_key: ${{ secrets.aws_secret_access_key }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "linux/amd64",
            platform: "linux/amd64",
            cache: "cache-amd64-stable",
            stableUnstable: "stable",
            runner: "ubuntu-latest",
            runnerType: "github-hosted"
          }
        - {
            name: "linux/arm64",
            platform: "linux/arm64",
            cache: "cache-arm64-stable",
            stableUnstable: "stable",
            runner: "debian-arm64",
            runnerType: "self-hosted"
          }

  # TODO build-docker-unstable:

  publish-manifest-stable:
    runs-on: "ubuntu-latest"
    needs: [build-docker-stable]

    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.docker_hub_username }}
        password: ${{ secrets.docker_hub_token }}

    - name: Publish Dockerhub manifest normal image
      run: ./local-build.sh version=stable image=normal type=ci step=publish-manifest currentTag=${{ inputs.current_branch_tag }}-stable pushTag=${{ inputs.current_branch_tag }} isTag=${{ inputs.is_tag }}

    - name: Publish Dockerhub manifest full image
      run: ./local-build.sh version=stable image=full type=ci step=publish-manifest currentTag=${{ inputs.current_branch_tag }}-full-stable pushTag=${{ inputs.current_branch_tag }}-full isTag=${{ inputs.is_tag }}


    - name: Update DockerHub repo description
      uses: peter-evans/dockerhub-description@v3
      if: inputs.is_tag == 'true'
      with:
        username: ${{ secrets.docker_hub_username }}
        password: ${{ secrets.docker_hub_token }}
        repository: orthancteam/orthanc
        readme-filepath: README-dockerhub.md
