name: build and release 2

on:
  push:
    branches: 
      - '*'
    tags:
      - '*'

  pull_request:
    branches: [ master ]

jobs:
  pre-build:
    name: pre-build
    runs-on: "ubuntu-latest"
    outputs:
      current_branch_tag: ${{steps.branch-name.outputs.current_branch}}
      is_tag: ${{steps.branch-name.outputs.is_tag}}
    steps:
      - name: Get branch/tag name
        id: branch-name
        uses: tj-actions/branch-names@v5.1
        # output: steps.branch-name.outputs.current_branch contains the branch or the tag

  build-windows-installer:
    name: build-windows-installer
    runs-on: "ubuntu-latest"
    needs: [pre-build]

    steps:
    
    - uses: actions/checkout@v2

    - name: Build installer
      run: ./ciBuildWindowsInstaller.sh
      working-directory: ./WindowsInstaller
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      

  build-docker:
    name: build-docker
    runs-on: "ubuntu-latest"
    needs: [pre-build]

    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        config: .github/buildkitd.toml

    - name: Build the osimis/orthanc Docker image (no push)
      uses: docker/build-push-action@v2
      with:
        context: docker/orthanc/
        push: false
        tags: osimis/orthanc:current
        cache-from: type=gha,scope=osimis-orthanc
        cache-to: type=gha,scope=osimis-orthanc

  push-docker-tag:
    name: push-docker-tag
    needs: [build-docker, pre-build]
    if: needs.pre-build.outputs.is_tag == 'true'
    runs-on: ubuntu-latest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the osimis/orthanc Docker image
      uses: docker/build-push-action@v2
      with:
        context: docker/orthanc/
        push: true
        tags: osimis/orthanc:${{ needs.pre-build.outputs.current_branch_tag }}
        cache-from: type=gha,scope=osimis-orthanc
        cache-to: type=gha,scope=osimis-orthanc


