on:
  workflow_call:
    outputs:
      is_tag: 
        value: ${{ jobs.pre_build.outputs.is_tag }}
      current_branch_tag: 
        value: ${{ jobs.pre_build.outputs.current_branch_tag }}

jobs:

  pre_build:
    name: pre_build
    runs-on: "ubuntu-latest"
    outputs:
      current_branch_tag: ${{steps.branch_name.outputs.current_branch_tag}}
      is_tag: ${{steps.branch_name.outputs.is_tag}}

    steps:
    - name: Get branch/tag name
      id: branch_name
      run: |
        echo "current_branch_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        [[ "${GITHUB_REF_TYPE}" == "tag" ]] && echo "is_tag=true" >> $GITHUB_OUTPUT || echo "is_tag=false" >> $GITHUB_OUTPUT

    - name: Echo pre_build
      run: |
        echo ${{ steps.branch_name.outputs.is_tag }} ${{ steps.branch_name.outputs.current_branch_tag }}
        echo ${{ github.ref}}

